name: d_chart
description: Simple way to show and use chart for Flutter with many option.
version: 2.10.4
homepage: https://github.com/indratrisnar/d_chart

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  community_charts_flutter: ^1.0.4
  community_charts_common: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
